// The shared Pokédex — the single source of truth for every Pokémon's id,
// sprite, and names, used by BOTH the Maths Quest and the Chinese Writing games.
//
// Sprites are the Gen-IV (HeartGold/SoulSilver) battle sprites, 80×80, served
// from /public/assets/pokemon/<sprite>.
//
// nameZh is Traditional Chinese: the classic Hong Kong names for Gen 1 (e.g.
// 比卡超 not 皮卡丘) and the Traditional names for Gen 2. Games that need to
// grade names by stroke count derive that themselves (see writing/data.ts).

export interface PokedexEntry {
  id: string
  sprite: string // filename in /assets/pokemon
  nameEn: string
  nameZh: string // Traditional Chinese name
  powerful?: boolean // a strong Pokémon — games may headline these as bosses
  // Evolution: when a buddy the player trains reaches `evolveLevel`, it evolves
  // into `evolvesTo` (another Pokédex id). Both are set together, or neither.
  evolvesTo?: string
  evolveLevel?: number
  legendary?: boolean
}

export const POKEDEX: PokedexEntry[] = [
  { id: 'bulbasaur', sprite: 'bulbasaur.png', nameEn: "Bulbasaur", nameZh: '奇異種子', evolvesTo: 'ivysaur', evolveLevel: 16 },
  { id: 'ivysaur', sprite: 'ivysaur.png', nameEn: "Ivysaur", nameZh: '奇異草', evolvesTo: 'venusaur', evolveLevel: 32 },
  { id: 'venusaur', sprite: 'venusaur.png', nameEn: "Venusaur", nameZh: '奇異花' , powerful: true },
  { id: 'charmander', sprite: 'charmander.png', nameEn: "Charmander", nameZh: '小火龍', evolvesTo: 'charmeleon', evolveLevel: 16 },
  { id: 'charmeleon', sprite: 'charmeleon.png', nameEn: "Charmeleon", nameZh: '火恐龍', evolvesTo: 'charizard', evolveLevel: 36 },
  { id: 'charizard', sprite: 'charizard.png', nameEn: "Charizard", nameZh: '噴火龍' , powerful: true },
  { id: 'squirtle', sprite: 'squirtle.png', nameEn: "Squirtle", nameZh: '車厘龜', evolvesTo: 'wartortle', evolveLevel: 16 },
  { id: 'wartortle', sprite: 'wartortle.png', nameEn: "Wartortle", nameZh: '卡美龜', evolvesTo: 'blastoise', evolveLevel: 36 },
  { id: 'blastoise', sprite: 'blastoise.png', nameEn: "Blastoise", nameZh: '水箭龜' , powerful: true },
  { id: 'caterpie', sprite: 'caterpie.png', nameEn: "Caterpie", nameZh: '綠毛蟲' },
  { id: 'metapod', sprite: 'metapod.png', nameEn: "Metapod", nameZh: '鐵甲蟲' },
  { id: 'butterfree', sprite: 'butterfree.png', nameEn: "Butterfree", nameZh: '巴他蝶' },
  { id: 'weedle', sprite: 'weedle.png', nameEn: "Weedle", nameZh: '獨角蟲' },
  { id: 'kakuna', sprite: 'kakuna.png', nameEn: "Kakuna", nameZh: '鐵殼蛹' },
  { id: 'beedrill', sprite: 'beedrill.png', nameEn: "Beedrill", nameZh: '大針蜂' },
  { id: 'pidgey', sprite: 'pidgey.png', nameEn: "Pidgey", nameZh: '波波' },
  { id: 'pidgeotto', sprite: 'pidgeotto.png', nameEn: "Pidgeotto", nameZh: '比比鳥' },
  { id: 'pidgeot', sprite: 'pidgeot.png', nameEn: "Pidgeot", nameZh: '大比鳥' },
  { id: 'rattata', sprite: 'rattata.png', nameEn: "Rattata", nameZh: '小哥達' },
  { id: 'raticate', sprite: 'raticate.png', nameEn: "Raticate", nameZh: '哥達' },
  { id: 'spearow', sprite: 'spearow.png', nameEn: "Spearow", nameZh: '鬼雀' },
  { id: 'fearow', sprite: 'fearow.png', nameEn: "Fearow", nameZh: '魔雀' },
  { id: 'ekans', sprite: 'ekans.png', nameEn: "Ekans", nameZh: '阿柏蛇' },
  { id: 'arbok', sprite: 'arbok.png', nameEn: "Arbok", nameZh: '阿柏怪' },
  // House rule: Pikachu→Raichu is a Thunder Stone evolution in canon (no level),
  // gated here at 16 to match a stage-1 line's first evolution.
  { id: 'pikachu', sprite: 'pikachu.png', nameEn: "Pikachu", nameZh: '比卡超', evolvesTo: 'raichu', evolveLevel: 16 },
  { id: 'raichu', sprite: 'raichu.png', nameEn: "Raichu", nameZh: '雷超' },
  { id: 'sandshrew', sprite: 'sandshrew.png', nameEn: "Sandshrew", nameZh: '穿山鼠' },
  { id: 'sandslash', sprite: 'sandslash.png', nameEn: "Sandslash", nameZh: '穿山王' },
  { id: 'nidoran-f', sprite: 'nidoran-f.png', nameEn: "Nidoran ♀", nameZh: '尼美蘭' },
  { id: 'nidorina', sprite: 'nidorina.png', nameEn: "Nidorina", nameZh: '尼美羅' },
  { id: 'nidoqueen', sprite: 'nidoqueen.png', nameEn: "Nidoqueen", nameZh: '尼美后' },
  { id: 'nidoran-m', sprite: 'nidoran-m.png', nameEn: "Nidoran ♂", nameZh: '尼多郎' },
  { id: 'nidorino', sprite: 'nidorino.png', nameEn: "Nidorino", nameZh: '尼多利' },
  { id: 'nidoking', sprite: 'nidoking.png', nameEn: "Nidoking", nameZh: '尼多王' },
  { id: 'clefairy', sprite: 'clefairy.png', nameEn: "Clefairy", nameZh: '皮皮' },
  { id: 'clefable', sprite: 'clefable.png', nameEn: "Clefable", nameZh: '皮可斯' },
  { id: 'vulpix', sprite: 'vulpix.png', nameEn: "Vulpix", nameZh: '六尾' },
  { id: 'ninetales', sprite: 'ninetales.png', nameEn: "Ninetales", nameZh: '九尾' },
  { id: 'jigglypuff', sprite: 'jigglypuff.png', nameEn: "Jigglypuff", nameZh: '波波球' },
  { id: 'wigglytuff', sprite: 'wigglytuff.png', nameEn: "Wigglytuff", nameZh: '肥波球' },
  { id: 'zubat', sprite: 'zubat.png', nameEn: "Zubat", nameZh: '波音蝠' },
  { id: 'golbat', sprite: 'golbat.png', nameEn: "Golbat", nameZh: '大口蝠' },
  { id: 'oddish', sprite: 'oddish.png', nameEn: "Oddish", nameZh: '行路草' },
  { id: 'gloom', sprite: 'gloom.png', nameEn: "Gloom", nameZh: '怪味花' },
  { id: 'vileplume', sprite: 'vileplume.png', nameEn: "Vileplume", nameZh: '霸王花' },
  { id: 'paras', sprite: 'paras.png', nameEn: "Paras", nameZh: '蘑菇蟲' },
  { id: 'parasect', sprite: 'parasect.png', nameEn: "Parasect", nameZh: '巨菇蟲' },
  { id: 'venonat', sprite: 'venonat.png', nameEn: "Venonat", nameZh: '毛毛蟲' },
  { id: 'venomoth', sprite: 'venomoth.png', nameEn: "Venomoth", nameZh: '魔魯風' },
  { id: 'diglett', sprite: 'diglett.png', nameEn: "Diglett", nameZh: '地鼠' },
  { id: 'dugtrio', sprite: 'dugtrio.png', nameEn: "Dugtrio", nameZh: '三頭地鼠' },
  { id: 'meowth', sprite: 'meowth.png', nameEn: "Meowth", nameZh: '喵喵怪' },
  { id: 'persian', sprite: 'persian.png', nameEn: "Persian", nameZh: '高竇貓' },
  { id: 'psyduck', sprite: 'psyduck.png', nameEn: "Psyduck", nameZh: '傻鴨' },
  { id: 'golduck', sprite: 'golduck.png', nameEn: "Golduck", nameZh: '高超鴨' },
  { id: 'mankey', sprite: 'mankey.png', nameEn: "Mankey", nameZh: '猴怪' },
  { id: 'primeape', sprite: 'primeape.png', nameEn: "Primeape", nameZh: '火爆猴' },
  { id: 'growlithe', sprite: 'growlithe.png', nameEn: "Growlithe", nameZh: '護主犬' },
  { id: 'arcanine', sprite: 'arcanine.png', nameEn: "Arcanine", nameZh: '奉神犬' , powerful: true },
  { id: 'poliwag', sprite: 'poliwag.png', nameEn: "Poliwag", nameZh: '蚊香蝌蚪' },
  { id: 'poliwhirl', sprite: 'poliwhirl.png', nameEn: "Poliwhirl", nameZh: '蚊香蛙' },
  { id: 'poliwrath', sprite: 'poliwrath.png', nameEn: "Poliwrath", nameZh: '大力蛙' },
  { id: 'abra', sprite: 'abra.png', nameEn: "Abra", nameZh: '卡斯' },
  { id: 'kadabra', sprite: 'kadabra.png', nameEn: "Kadabra", nameZh: '尤基納' },
  { id: 'alakazam', sprite: 'alakazam.png', nameEn: "Alakazam", nameZh: '富迪' , powerful: true },
  { id: 'machop', sprite: 'machop.png', nameEn: "Machop", nameZh: '鐵腕' },
  { id: 'machoke', sprite: 'machoke.png', nameEn: "Machoke", nameZh: '大力' },
  { id: 'machamp', sprite: 'machamp.png', nameEn: "Machamp", nameZh: '怪力' , powerful: true },
  { id: 'bellsprout', sprite: 'bellsprout.png', nameEn: "Bellsprout", nameZh: '喇叭芽' },
  { id: 'weepinbell', sprite: 'weepinbell.png', nameEn: "Weepinbell", nameZh: '口呆花' },
  { id: 'victreebel', sprite: 'victreebel.png', nameEn: "Victreebel", nameZh: '大食花' },
  { id: 'tentacool', sprite: 'tentacool.png', nameEn: "Tentacool", nameZh: '大眼水母' },
  { id: 'tentacruel', sprite: 'tentacruel.png', nameEn: "Tentacruel", nameZh: '多腳水母' },
  { id: 'geodude', sprite: 'geodude.png', nameEn: "Geodude", nameZh: '小拳石' },
  { id: 'graveler', sprite: 'graveler.png', nameEn: "Graveler", nameZh: '滾動石' },
  { id: 'golem', sprite: 'golem.png', nameEn: "Golem", nameZh: '滾動岩' , powerful: true },
  { id: 'ponyta', sprite: 'ponyta.png', nameEn: "Ponyta", nameZh: '小火馬' },
  { id: 'rapidash', sprite: 'rapidash.png', nameEn: "Rapidash", nameZh: '烈焰馬' },
  { id: 'slowpoke', sprite: 'slowpoke.png', nameEn: "Slowpoke", nameZh: '小呆獸' },
  { id: 'slowbro', sprite: 'slowbro.png', nameEn: "Slowbro", nameZh: '大呆獸' },
  { id: 'magnemite', sprite: 'magnemite.png', nameEn: "Magnemite", nameZh: '小磁怪' },
  { id: 'magneton', sprite: 'magneton.png', nameEn: "Magneton", nameZh: '三合一磁怪' },
  { id: 'farfetchd', sprite: 'farfetchd.png', nameEn: "Farfetch'd", nameZh: '火蔥鴨' },
  { id: 'doduo', sprite: 'doduo.png', nameEn: "Doduo", nameZh: '多多' },
  { id: 'dodrio', sprite: 'dodrio.png', nameEn: "Dodrio", nameZh: '多多利' },
  { id: 'seel', sprite: 'seel.png', nameEn: "Seel", nameZh: '小海獅' },
  { id: 'dewgong', sprite: 'dewgong.png', nameEn: "Dewgong", nameZh: '白海獅' },
  { id: 'grimer', sprite: 'grimer.png', nameEn: "Grimer", nameZh: '爛泥怪' },
  { id: 'muk', sprite: 'muk.png', nameEn: "Muk", nameZh: '爛泥獸' },
  { id: 'shellder', sprite: 'shellder.png', nameEn: "Shellder", nameZh: '貝殼怪' },
  { id: 'cloyster', sprite: 'cloyster.png', nameEn: "Cloyster", nameZh: '鐵甲貝' },
  { id: 'gastly', sprite: 'gastly.png', nameEn: "Gastly", nameZh: '鬼斯' },
  { id: 'haunter', sprite: 'haunter.png', nameEn: "Haunter", nameZh: '鬼斯通' },
  { id: 'gengar', sprite: 'gengar.png', nameEn: "Gengar", nameZh: '耿鬼' , powerful: true },
  { id: 'onix', sprite: 'onix.png', nameEn: "Onix", nameZh: '大岩蛇' },
  { id: 'drowzee', sprite: 'drowzee.png', nameEn: "Drowzee", nameZh: '食夢獸' },
  { id: 'hypno', sprite: 'hypno.png', nameEn: "Hypno", nameZh: '催眠獸' },
  { id: 'krabby', sprite: 'krabby.png', nameEn: "Krabby", nameZh: '大鉗蟹' },
  { id: 'kingler', sprite: 'kingler.png', nameEn: "Kingler", nameZh: '巨鉗蟹' },
  { id: 'voltorb', sprite: 'voltorb.png', nameEn: "Voltorb", nameZh: '霹靂彈' },
  { id: 'electrode', sprite: 'electrode.png', nameEn: "Electrode", nameZh: '雷霆彈' },
  { id: 'exeggcute', sprite: 'exeggcute.png', nameEn: "Exeggcute", nameZh: '蛋蛋' },
  { id: 'exeggutor', sprite: 'exeggutor.png', nameEn: "Exeggutor", nameZh: '椰樹獸' },
  { id: 'cubone', sprite: 'cubone.png', nameEn: "Cubone", nameZh: '卡拉卡拉' },
  { id: 'marowak', sprite: 'marowak.png', nameEn: "Marowak", nameZh: '格拉格拉' },
  { id: 'hitmonlee', sprite: 'hitmonlee.png', nameEn: "Hitmonlee", nameZh: '沙古拉' },
  { id: 'hitmonchan', sprite: 'hitmonchan.png', nameEn: "Hitmonchan", nameZh: '比華拉' },
  { id: 'lickitung', sprite: 'lickitung.png', nameEn: "Lickitung", nameZh: '大舌頭' },
  { id: 'koffing', sprite: 'koffing.png', nameEn: "Koffing", nameZh: '毒氣丸' },
  { id: 'weezing', sprite: 'weezing.png', nameEn: "Weezing", nameZh: '毒氣雙子' },
  { id: 'rhyhorn', sprite: 'rhyhorn.png', nameEn: "Rhyhorn", nameZh: '鐵甲犀牛' },
  { id: 'rhydon', sprite: 'rhydon.png', nameEn: "Rhydon", nameZh: '鐵甲暴龍' },
  { id: 'chansey', sprite: 'chansey.png', nameEn: "Chansey", nameZh: '吉利蛋' },
  { id: 'tangela', sprite: 'tangela.png', nameEn: "Tangela", nameZh: '長藤怪' },
  { id: 'kangaskhan', sprite: 'kangaskhan.png', nameEn: "Kangaskhan", nameZh: '袋獸' },
  { id: 'horsea', sprite: 'horsea.png', nameEn: "Horsea", nameZh: '噴墨海馬' },
  { id: 'seadra', sprite: 'seadra.png', nameEn: "Seadra", nameZh: '飛刺海馬' },
  { id: 'goldeen', sprite: 'goldeen.png', nameEn: "Goldeen", nameZh: '獨角金魚' },
  { id: 'seaking', sprite: 'seaking.png', nameEn: "Seaking", nameZh: '金魚王' },
  { id: 'staryu', sprite: 'staryu.png', nameEn: "Staryu", nameZh: '海星星' },
  { id: 'starmie', sprite: 'starmie.png', nameEn: "Starmie", nameZh: '寶石海星' },
  { id: 'mr-mime', sprite: 'mr-mime.png', nameEn: "Mr. Mime", nameZh: '吸盤小丑' },
  { id: 'scyther', sprite: 'scyther.png', nameEn: "Scyther", nameZh: '飛天螳螂' },
  { id: 'jynx', sprite: 'jynx.png', nameEn: "Jynx", nameZh: '紅唇娃' },
  { id: 'electabuzz', sprite: 'electabuzz.png', nameEn: "Electabuzz", nameZh: '電擊獸' },
  { id: 'magmar', sprite: 'magmar.png', nameEn: "Magmar", nameZh: '鴨嘴火龍' },
  { id: 'pinsir', sprite: 'pinsir.png', nameEn: "Pinsir", nameZh: '鉗刀甲蟲' },
  { id: 'tauros', sprite: 'tauros.png', nameEn: "Tauros", nameZh: '大隻牛' },
  { id: 'magikarp', sprite: 'magikarp.png', nameEn: "Magikarp", nameZh: '鯉魚王' },
  { id: 'gyarados', sprite: 'gyarados.png', nameEn: "Gyarados", nameZh: '鯉魚龍' , powerful: true },
  { id: 'lapras', sprite: 'lapras.png', nameEn: "Lapras", nameZh: '背背龍' , powerful: true },
  { id: 'ditto', sprite: 'ditto.png', nameEn: "Ditto", nameZh: '百變怪' },
  // House rule: Eevee→Vaporeon is a Water Stone evolution in canon (no level),
  // gated here at 16 to match a stage-1 line's first evolution.
  { id: 'eevee', sprite: 'eevee.png', nameEn: "Eevee", nameZh: '伊貝', evolvesTo: 'vaporeon', evolveLevel: 16 },
  { id: 'vaporeon', sprite: 'vaporeon.png', nameEn: "Vaporeon", nameZh: '水伊貝', legendary: true },
  { id: 'jolteon', sprite: 'jolteon.png', nameEn: "Jolteon", nameZh: '雷伊貝', legendary: true },
  { id: 'flareon', sprite: 'flareon.png', nameEn: "Flareon", nameZh: '火伊貝', legendary: true },
  { id: 'porygon', sprite: 'porygon.png', nameEn: "Porygon", nameZh: '立方獸' },
  { id: 'omanyte', sprite: 'omanyte.png', nameEn: "Omanyte", nameZh: '菊石獸' },
  { id: 'omastar', sprite: 'omastar.png', nameEn: "Omastar", nameZh: '多刺菊石獸' },
  { id: 'kabuto', sprite: 'kabuto.png', nameEn: "Kabuto", nameZh: '萬年蟲' },
  { id: 'kabutops', sprite: 'kabutops.png', nameEn: "Kabutops", nameZh: '鐮刀蟲' },
  { id: 'aerodactyl', sprite: 'aerodactyl.png', nameEn: "Aerodactyl", nameZh: '化石飛龍' , powerful: true },
  { id: 'snorlax', sprite: 'snorlax.png', nameEn: "Snorlax", nameZh: '卡比獸' , powerful: true },
  { id: 'articuno', sprite: 'articuno.png', nameEn: "Articuno", nameZh: '急凍鳥' , powerful: true, legendary: true },
  { id: 'zapdos', sprite: 'zapdos.png', nameEn: "Zapdos", nameZh: '雷鳥' , powerful: true, legendary: true },
  { id: 'moltres', sprite: 'moltres.png', nameEn: "Moltres", nameZh: '火鳥' , powerful: true, legendary: true },
  { id: 'dratini', sprite: 'dratini.png', nameEn: "Dratini", nameZh: '迷你龍' },
  { id: 'dragonair', sprite: 'dragonair.png', nameEn: "Dragonair", nameZh: '哈古龍' },
  { id: 'dragonite', sprite: 'dragonite.png', nameEn: "Dragonite", nameZh: '啟暴龍' , powerful: true },
  { id: 'mewtwo', sprite: 'mewtwo.png', nameEn: "Mewtwo", nameZh: '超夢夢' , powerful: true, legendary: true },
  { id: 'mew', sprite: 'mew.png', nameEn: "Mew", nameZh: '夢夢' , powerful: true, legendary: true },
  { id: 'chikorita', sprite: 'chikorita.png', nameEn: "Chikorita", nameZh: '菊草葉' },
  { id: 'bayleef', sprite: 'bayleef.png', nameEn: "Bayleef", nameZh: '月桂葉' },
  { id: 'meganium', sprite: 'meganium.png', nameEn: "Meganium", nameZh: '大竺葵' , powerful: true },
  { id: 'cyndaquil', sprite: 'cyndaquil.png', nameEn: "Cyndaquil", nameZh: '火球鼠' },
  { id: 'quilava', sprite: 'quilava.png', nameEn: "Quilava", nameZh: '火岩鼠' },
  { id: 'typhlosion', sprite: 'typhlosion.png', nameEn: "Typhlosion", nameZh: '火爆獸' , powerful: true },
  { id: 'totodile', sprite: 'totodile.png', nameEn: "Totodile", nameZh: '小鋸鱷' },
  { id: 'croconaw', sprite: 'croconaw.png', nameEn: "Croconaw", nameZh: '藍鱷' },
  { id: 'feraligatr', sprite: 'feraligatr.png', nameEn: "Feraligatr", nameZh: '大力鱷' , powerful: true },
  { id: 'sentret', sprite: 'sentret.png', nameEn: "Sentret", nameZh: '尾立' },
  { id: 'furret', sprite: 'furret.png', nameEn: "Furret", nameZh: '大尾立' },
  { id: 'hoothoot', sprite: 'hoothoot.png', nameEn: "Hoothoot", nameZh: '咕咕' },
  { id: 'noctowl', sprite: 'noctowl.png', nameEn: "Noctowl", nameZh: '貓頭夜鷹' },
  { id: 'ledyba', sprite: 'ledyba.png', nameEn: "Ledyba", nameZh: '芭瓢蟲' },
  { id: 'ledian', sprite: 'ledian.png', nameEn: "Ledian", nameZh: '安瓢蟲' },
  { id: 'spinarak', sprite: 'spinarak.png', nameEn: "Spinarak", nameZh: '圓絲蛛' },
  { id: 'ariados', sprite: 'ariados.png', nameEn: "Ariados", nameZh: '阿利多斯' },
  { id: 'crobat', sprite: 'crobat.png', nameEn: "Crobat", nameZh: '叉字蝠' },
  { id: 'chinchou', sprite: 'chinchou.png', nameEn: "Chinchou", nameZh: '燈籠魚' },
  { id: 'lanturn', sprite: 'lanturn.png', nameEn: "Lanturn", nameZh: '電燈怪' },
  { id: 'pichu', sprite: 'pichu.png', nameEn: "Pichu", nameZh: '比超' },
  { id: 'cleffa', sprite: 'cleffa.png', nameEn: "Cleffa", nameZh: '皮寶寶' },
  { id: 'igglybuff', sprite: 'igglybuff.png', nameEn: "Igglybuff", nameZh: '小波球' },
  { id: 'togepi', sprite: 'togepi.png', nameEn: "Togepi", nameZh: '小刺蛋' },
  { id: 'togetic', sprite: 'togetic.png', nameEn: "Togetic", nameZh: '波克基古' },
  { id: 'natu', sprite: 'natu.png', nameEn: "Natu", nameZh: '天然雀' },
  { id: 'xatu', sprite: 'xatu.png', nameEn: "Xatu", nameZh: '天然鳥' },
  { id: 'mareep', sprite: 'mareep.png', nameEn: "Mareep", nameZh: '咩利羊' },
  { id: 'flaaffy', sprite: 'flaaffy.png', nameEn: "Flaaffy", nameZh: '茸茸羊' },
  { id: 'ampharos', sprite: 'ampharos.png', nameEn: "Ampharos", nameZh: '電龍' , powerful: true },
  { id: 'bellossom', sprite: 'bellossom.png', nameEn: "Bellossom", nameZh: '美麗花' },
  { id: 'marill', sprite: 'marill.png', nameEn: "Marill", nameZh: '馬利露' },
  { id: 'azumarill', sprite: 'azumarill.png', nameEn: "Azumarill", nameZh: '馬利露麗' },
  { id: 'sudowoodo', sprite: 'sudowoodo.png', nameEn: "Sudowoodo", nameZh: '樹才怪' },
  { id: 'politoed', sprite: 'politoed.png', nameEn: "Politoed", nameZh: '蚊香蛙皇' },
  { id: 'hoppip', sprite: 'hoppip.png', nameEn: "Hoppip", nameZh: '毽子草' },
  { id: 'skiploom', sprite: 'skiploom.png', nameEn: "Skiploom", nameZh: '毽子花' },
  { id: 'jumpluff', sprite: 'jumpluff.png', nameEn: "Jumpluff", nameZh: '毽子棉' },
  { id: 'aipom', sprite: 'aipom.png', nameEn: "Aipom", nameZh: '長尾怪手' },
  { id: 'sunkern', sprite: 'sunkern.png', nameEn: "Sunkern", nameZh: '向日種子' },
  { id: 'sunflora', sprite: 'sunflora.png', nameEn: "Sunflora", nameZh: '向日花怪' },
  { id: 'yanma', sprite: 'yanma.png', nameEn: "Yanma", nameZh: '蜻蜻蜓' },
  { id: 'wooper', sprite: 'wooper.png', nameEn: "Wooper", nameZh: '烏波' },
  { id: 'quagsire', sprite: 'quagsire.png', nameEn: "Quagsire", nameZh: '沼王' },
  { id: 'espeon', sprite: 'espeon.png', nameEn: "Espeon", nameZh: '太陽伊貝' },
  { id: 'umbreon', sprite: 'umbreon.png', nameEn: "Umbreon", nameZh: '月亮伊貝' },
  { id: 'murkrow', sprite: 'murkrow.png', nameEn: "Murkrow", nameZh: '黑暗鴉' },
  { id: 'slowking', sprite: 'slowking.png', nameEn: "Slowking", nameZh: '呆呆王' },
  { id: 'misdreavus', sprite: 'misdreavus.png', nameEn: "Misdreavus", nameZh: '夢妖' },
  { id: 'unown', sprite: 'unown.png', nameEn: "Unown", nameZh: '未知圖騰' },
  { id: 'wobbuffet', sprite: 'wobbuffet.png', nameEn: "Wobbuffet", nameZh: '果然翁' },
  { id: 'girafarig', sprite: 'girafarig.png', nameEn: "Girafarig", nameZh: '麒麟奇' },
  { id: 'pineco', sprite: 'pineco.png', nameEn: "Pineco", nameZh: '榛果球' },
  { id: 'forretress', sprite: 'forretress.png', nameEn: "Forretress", nameZh: '佛烈托斯' },
  { id: 'dunsparce', sprite: 'dunsparce.png', nameEn: "Dunsparce", nameZh: '土龍弟弟' },
  { id: 'gligar', sprite: 'gligar.png', nameEn: "Gligar", nameZh: '天蠍' },
  { id: 'steelix', sprite: 'steelix.png', nameEn: "Steelix", nameZh: '大鋼蛇' , powerful: true },
  { id: 'snubbull', sprite: 'snubbull.png', nameEn: "Snubbull", nameZh: '布魯' },
  { id: 'granbull', sprite: 'granbull.png', nameEn: "Granbull", nameZh: '布魯皇' },
  { id: 'qwilfish', sprite: 'qwilfish.png', nameEn: "Qwilfish", nameZh: '千針魚' },
  { id: 'scizor', sprite: 'scizor.png', nameEn: "Scizor", nameZh: '巨鉗螳螂' },
  { id: 'shuckle', sprite: 'shuckle.png', nameEn: "Shuckle", nameZh: '壺壺' },
  { id: 'heracross', sprite: 'heracross.png', nameEn: "Heracross", nameZh: '赫拉克羅斯' },
  { id: 'sneasel', sprite: 'sneasel.png', nameEn: "Sneasel", nameZh: '狃拉' },
  { id: 'teddiursa', sprite: 'teddiursa.png', nameEn: "Teddiursa", nameZh: '熊寶寶' },
  { id: 'ursaring', sprite: 'ursaring.png', nameEn: "Ursaring", nameZh: '圈圈熊' },
  { id: 'slugma', sprite: 'slugma.png', nameEn: "Slugma", nameZh: '熔岩蟲' },
  { id: 'magcargo', sprite: 'magcargo.png', nameEn: "Magcargo", nameZh: '熔岩蝸牛' },
  { id: 'swinub', sprite: 'swinub.png', nameEn: "Swinub", nameZh: '小山豬' },
  { id: 'piloswine', sprite: 'piloswine.png', nameEn: "Piloswine", nameZh: '長毛豬' },
  { id: 'corsola', sprite: 'corsola.png', nameEn: "Corsola", nameZh: '太陽珊瑚' },
  { id: 'remoraid', sprite: 'remoraid.png', nameEn: "Remoraid", nameZh: '鐵炮魚' },
  { id: 'octillery', sprite: 'octillery.png', nameEn: "Octillery", nameZh: '章魚桶' },
  { id: 'delibird', sprite: 'delibird.png', nameEn: "Delibird", nameZh: '信使鳥' },
  { id: 'mantine', sprite: 'mantine.png', nameEn: "Mantine", nameZh: '巨翅飛魚' },
  { id: 'skarmory', sprite: 'skarmory.png', nameEn: "Skarmory", nameZh: '盔甲鳥' },
  { id: 'houndour', sprite: 'houndour.png', nameEn: "Houndour", nameZh: '戴魯比' },
  { id: 'houndoom', sprite: 'houndoom.png', nameEn: "Houndoom", nameZh: '黑魯加' },
  { id: 'kingdra', sprite: 'kingdra.png', nameEn: "Kingdra", nameZh: '刺龍王' },
  { id: 'phanpy', sprite: 'phanpy.png', nameEn: "Phanpy", nameZh: '小小象' },
  { id: 'donphan', sprite: 'donphan.png', nameEn: "Donphan", nameZh: '冬凡' },
  { id: 'porygon2', sprite: 'porygon2.png', nameEn: "Porygon2", nameZh: '立方獸Ⅱ' },
  { id: 'stantler', sprite: 'stantler.png', nameEn: "Stantler", nameZh: '驚角鹿' },
  { id: 'smeargle', sprite: 'smeargle.png', nameEn: "Smeargle", nameZh: '圖圖犬' },
  { id: 'tyrogue', sprite: 'tyrogue.png', nameEn: "Tyrogue", nameZh: '無畏小子' },
  { id: 'hitmontop', sprite: 'hitmontop.png', nameEn: "Hitmontop", nameZh: '戰舞郎' },
  { id: 'smoochum', sprite: 'smoochum.png', nameEn: "Smoochum", nameZh: '迷唇娃' },
  { id: 'elekid', sprite: 'elekid.png', nameEn: "Elekid", nameZh: '電擊怪' },
  { id: 'magby', sprite: 'magby.png', nameEn: "Magby", nameZh: '鴨嘴寶寶' },
  { id: 'miltank', sprite: 'miltank.png', nameEn: "Miltank", nameZh: '大奶罐' },
  { id: 'blissey', sprite: 'blissey.png', nameEn: "Blissey", nameZh: '幸福蛋' },
  { id: 'raikou', sprite: 'raikou.png', nameEn: "Raikou", nameZh: '雷公' , powerful: true, legendary: true },
  { id: 'entei', sprite: 'entei.png', nameEn: "Entei", nameZh: '炎帝' , powerful: true, legendary: true },
  { id: 'suicune', sprite: 'suicune.png', nameEn: "Suicune", nameZh: '水君' , powerful: true, legendary: true },
  { id: 'larvitar', sprite: 'larvitar.png', nameEn: "Larvitar", nameZh: '幼基拉斯' },
  { id: 'pupitar', sprite: 'pupitar.png', nameEn: "Pupitar", nameZh: '沙基拉斯' },
  { id: 'tyranitar', sprite: 'tyranitar.png', nameEn: "Tyranitar", nameZh: '班基拉斯' , powerful: true },
  { id: 'lugia', sprite: 'lugia.png', nameEn: "Lugia", nameZh: '利基亞' , powerful: true, legendary: true },
  { id: 'ho-oh', sprite: 'ho-oh.png', nameEn: "Ho-Oh", nameZh: '鳳凰' , powerful: true, legendary: true },
  { id: 'celebi', sprite: 'celebi.png', nameEn: "Celebi", nameZh: '時拉比' , powerful: true, legendary: true },
]

const BY_ID: Record<string, PokedexEntry> = Object.fromEntries(
  POKEDEX.map((p) => [p.id, p]),
)

/** Look up a Pokédex entry by its id (undefined if unknown). */
export function pokedexEntry(id: string): PokedexEntry | undefined {
  return BY_ID[id]
}

/** Walk a Pokémon's evolution chain, applying every evolution whose level the
 *  given buddy level has reached. Returns the current (possibly evolved) id.
 *  Unknown ids are returned unchanged. */
export function evolvedSpecies(baseId: string, level: number): string {
  let id = baseId
  // Guard the loop so a malformed self-referential chain can't spin forever.
  for (let step = 0; step < 10; step++) {
    const entry = BY_ID[id]
    if (entry?.evolvesTo && entry.evolveLevel != null && level >= entry.evolveLevel) {
      id = entry.evolvesTo
    } else {
      break
    }
  }
  return id
}

/** Legendary / powerful Pokémon, suitable for headlining as a boss. */
export const BOSS_POKEMON: PokedexEntry[] = POKEDEX.filter((p) => p.powerful)

/** Every rank-and-file Pokémon — everything not flagged as a boss. */
export const REGULAR_POKEMON: PokedexEntry[] = POKEDEX.filter((p) => !p.powerful)
